on: [push, pull_request]

name: unit-tests

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - go-version: 1.16.x
            target: test
          - go-version: 1.15.x
            target: go-test-internal test-adapter-postgresql test-adapter-cockroachdb test-adapter-mysql test-adapter-mssql test-adapter-sqlite test-adapter-mongo
          - go-version: 1.14.x
            target: go-test-internal test-adapter-postgresql test-adapter-cockroachdb test-adapter-mysql test-adapter-mssql test-adapter-sqlite test-adapter-mongo

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set env vars
        run: |
          echo "GOARCH=amd64" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "UPPER_DB_LOG=ERROR" >> $GITHUB_ENV

      - name: Execute target
        run: make ${{ matrix.target }}
