on: [push, pull_request]

name: unit-tests

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.14.x, 1.15.x, 1.16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set env vars
        run: |
          echo "GOARCH=amd64" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "UPPER_DB_LOG=ERROR" >> $GITHUB_ENV

      - name: Run target
        run: make test
